# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "opscode-centos65"
  config.vm.network :private_network, ip: "192.168.33.101"

  config.vm.provision :shell, :inline => <<-EOT
    yum -y install httpd php
    cp -a /vagrant/provision/httpd.conf /etc/httpd/conf/
    chkconfig httpd on
    service httpd restart
  EOT
end
